import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Roboto } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/layouts/navbar";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/layouts/footer";
import { TooltipProvider } from "@/components/ui/tooltip";

const robotoHeading = Roboto({subsets:['latin'],variable:'--font-heading'});

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Estambay Moto Rental",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable, robotoHeading.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-[#051424]/80">
        <ThemeProvider attribute="class"
                       defaultTheme="dark"
                       enableSystem
                       disableTransitionOnChange>
          <TooltipProvider>
            <header>
              <Navbar />
            </header>
            {children}
            <Footer />
          </TooltipProvider>
          <Toaster position="bottom-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
